version: '3.8'

services:
  taskmanager-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - taskmanager-db

  taskmanager-db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: YourStrong@Passw0rd
      ACCEPT_EULA: Y
      MSSQL_USER: taskmanagerdb   # Adiciona o usuário taskmanagerdb
      MSSQL_PASSWORD: YourStrong@Passw0rd  # Define a senha para o usuário taskmanagerdb
    ports:
      - "3004:1433"
    volumes:
      - ./DbObjects/setup.sql:/docker-entrypoint-initdb.d/setup.sql