  version: "3.8"

  networks:
    task_manager_networking:
      driver: bridge

  services:
    mssqldata:
      image: mcr.microsoft.com/mssql/server:latest
      networks:
        - task_manager_networking

    taskmanager-api:
      container_name: taskmanager-api
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - "3000:80"
      depends_on:
        - taskmanager-sql
      networks: 
        - task_manager_networking

    taskmanager-sql:
      image: mcr.microsoft.com/mssql/server:latest
      container_name: taskmanager-sql
      hostname: taskmanagersql
      ports:
        - "3004:1433"
      volumes:
        - /var/opt/mssql
        - ./:/usr/src/app
      working_dir: /usr/src/app
      command: sh -c ' chmod +x ./entrypoint.sh; ./entrypoint.sh & /opt/mssql/bin/sqlservr;'
      environment:
        SA_PASSWORD: YourStrong@Passw0rd
        ACCEPT_EULA: Y
        DATABASE_NAME: TaskManager
      volumes_from:
        - mssqldata
      networks: 
        - task_manager_networking