  version: "3.8"

  networks:
    task_manager_networking:
      driver: bridge

  services:
    taskmanager-api:
      container_name: taskmanager-api
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - "3000:80"
      depends_on:
        - taskmanager-sql
      networks: 
        - task_manager_networking

    taskmanager-sql:
      image: mcr.microsoft.com/mssql/server:latest
      container_name: taskmanager-sql
      volumes:
        - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
      environment:
        SA_PASSWORD: YourStrong@Passw0rd
        ACCEPT_EULA: Y
      ports:
        - "3004:1433"
      networks: 
        - task_manager_networking